---
title: Thorsten Abrahamczik
baseURL: "/"
params:
  palette: blue
  header:
    title: thorsten.abrahamczik.com
    logo_img: "/images/logo.svg"
    has_nav: true
    menu:
      actions: []
  footer:
    logo_img: images/logo_alt.png
    tagline: Produktmanagement, Webanalyse & SEO
    has_nav: true
    nav_title: Allgemeines
    has_social: true
    social_title: Social
    has_subscribe: false
    subscribe_title: Jetzt anmelden!
    subscribe_content: Bleibe mit den aktuellen Entwicklungen auf dem Laufenden
    content: "&copy; [year] thorsten.abrahamczik.com"
    links: []
disableKinds:
- RSS
- taxonomy
- taxonomyTerm
